services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: production
    network_mode: host
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/rails
      - /rails/public/assets # To prevent deleting precompiled assets.
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      SECRET_KEY_BASE: 462d54c7b15dcc1924e797d0b28e6d
      RAILS_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      ASSUME_SSL: false
      FORCE_SSL: false
    stdin_open: true
    tty: true

volumes:
  bundle:
