services:
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ats
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ats_production
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: production
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/rails
      - /rails/public/assets # To prevent deleting precompiled assets.
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      SECRET_KEY_BASE: 462d54c7b15dcc1924e797d0b28e6d
      RAILS_ENV: production
      DATABASE_URL: postgres://ats:password@db:5432/ats_production
      ASSUME_SSL: false
      FORCE_SSL: false
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  bundle:
